# Generated by Django 2.2.3 on 2019-07-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('product_id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('product_price', models.DateTimeField()),
            ],
        ),
    ]
