# Generated by Django 2.2.3 on 2019-07-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='product_price',
            field=models.IntegerField(),
        ),
    ]
